app = 'atn-bot'
primary_region = 'ams'

[build]

[deploy]
  strategy = "bluegreen"

[env]
  DB_PATH = '/app/data/attendance.db'
  DEFAULT_LANGUAGE = 'en'
  LOG_LEVEL = 'INFO'
  TIMEZONE = 'Asia/Tashkent'

# Health checks
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 2

  # Health check
  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[mounts]]
  source = 'attendance_data'
  destination = '/app/data'
  initial_size = '1gb'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
