# fly.toml app configuration file generated for atn-bot on 2025-10-18T20:58:33+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'atn-bot'
primary_region = 'ams'

[build]

[env]
  DB_PATH = '/app/data/attendance.db'
  DEFAULT_LANGUAGE = 'en'
  LOG_LEVEL = 'INFO'
  TIMEZONE = 'Asia/Tashkent'

[[mounts]]
  source = 'attendance_data'
  destination = '/app/data'
  initial_size = '1gb'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
